spring:
  application:
    name: nagginggnome
  mvc:
    servlet:
      path: /api
  profiles:
    include: { $SPRING_PROFILES_ACTIVE }

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

jwt:
  secret: ${JWT_SECRET}
  access-token-exp: ${ACCESS_TOKEN_EXP:3600}
  refresh-token-exp: ${REFRESH_TOKEN_EXP:1209600}
  issuer: ${JWT_ISSUER:nagginggnome}
