CREATE TABLE IF NOT EXISTS public.server_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id uuid NOT NULL,
    plan_id uuid NOT NULL,
    title varchar NOT NULL,
    body varchar NOT NULL,
    data_json jsonb NOT NULL,
    type varchar(32) NOT NULL,
    llm_meta_json jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT pk_server_messages PRIMARY KEY (id),

    CONSTRAINT fk_server_messages_user_id
        FOREIGN KEY (user_id)
        REFERENCES public.users(id),

    CONSTRAINT fk_server_messages_plan_id
        FOREIGN KEY (plan_id)
        REFERENCES public.plans(id),

    CONSTRAINT ck_server_messages_type
        CHECK (type IN ('REMINDER', 'ADDITIONAL'))
);

ALTER TABLE public.chat_messages
    ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS public.chat_message_seq;
ALTER TABLE public.chat_messages
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.push_jobs
    ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS public.push_jobs_id_seq;
ALTER TABLE public.push_jobs
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

DO $$
DECLARE
    next_chat_message_id bigint;
    next_push_job_id bigint;
BEGIN
    SELECT COALESCE(MAX(id), 0) + 1 INTO next_chat_message_id FROM public.chat_messages;
    EXECUTE format('ALTER TABLE public.chat_messages ALTER COLUMN id RESTART WITH %s', next_chat_message_id);

    SELECT COALESCE(MAX(id), 0) + 1 INTO next_push_job_id FROM public.push_jobs;
    EXECUTE format('ALTER TABLE public.push_jobs ALTER COLUMN id RESTART WITH %s', next_push_job_id);
END $$;
