CREATE TABLE IF NOT EXISTS public.user_summaries (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id uuid NOT NULL,
    summary_json jsonb NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT pk_user_summaries PRIMARY KEY (id),

    CONSTRAINT fk_user_summaries_user_id
        FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE INDEX IF NOT EXISTS idx_user_summaries_user_id
    ON public.user_summaries (user_id);

CREATE INDEX IF NOT EXISTS idx_user_summaries_created_at
    ON public.user_summaries (created_at);

ALTER TABLE public.llm_jobs
    DROP CONSTRAINT IF EXISTS pk_llm_jobs;
ALTER TABLE public.llm_jobs
    DROP COLUMN IF EXISTS id;
ALTER TABLE public.llm_jobs
    ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE public.llm_jobs
    ADD CONSTRAINT pk_llm_jobs PRIMARY KEY (id);

CREATE INDEX IF NOT EXISTS idx_llm_jobs_pending
    ON public.llm_jobs (id)
    WHERE status = 'PENDING';

CREATE INDEX IF NOT EXISTS idx_llm_jobs_success_unapplied
    ON public.llm_jobs (id)
    WHERE status = 'SUCCESS' AND applied_at IS NULL;

CREATE OR REPLACE FUNCTION public.notify_llm_job_request()
RETURNS trigger AS $$
BEGIN
    PERFORM pg_notify('llm_job_request', NEW.id::text);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_llm_jobs_notify_request ON public.llm_jobs;

CREATE TRIGGER tr_llm_jobs_notify_request
    AFTER INSERT ON public.llm_jobs
    FOR EACH ROW
    EXECUTE FUNCTION public.notify_llm_job_request();
